import {
  AlertCircle,
  AlertTriangle,
  ArrowLeftRight,
  BrainCircuit,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Coins,
  Download,
  Eye,
  EyeOff,
  Loader2,
  LogOut,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  PieChart,
  Plus,
  Radio,
  RefreshCw,
  RotateCcw,
  Send,
  Sparkles,
  Sun,
  Trash2,
  Upload,
  X,
  type LucideIcon,
} from "lucide-react";

const iconRegistry: Record<string, LucideIcon> = {
  alert_circle: AlertCircle,
  alert_triangle: AlertTriangle,
  arrow_swap: ArrowLeftRight,
  brain: BrainCircuit,
  camera: Camera,
  check: Check,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  close: X,
  coins: Coins,
  delete: Trash2,
  download: Download,
  edit: Pencil,
  eye: Eye,
  eye_off: EyeOff,
  loading: Loader2,
  logout: LogOut,
  moon: Moon,
  panel_left_close: PanelLeftClose,
  panel_left_open: PanelLeftOpen,
  pencil: Pencil,
  pie_chart: PieChart,
  plus: Plus,
  radio: Radio,
  refresh: RefreshCw,
  reset: RotateCcw,
  send: Send,
  sparkles: Sparkles,
  sun: Sun,
  trash: Trash2,
  upload: Upload,
};

export function getIcon(name: string): LucideIcon | null {
  const normalized = name.replace(/-/g, "_");
  return iconRegistry[normalized] ?? iconRegistry[name] ?? null;
}
